### ISSUE TITLE
multilingual input support improvement?

### ISSUE THREAD

**Issue by c933103** [GusCaplan/googlebot#3]
Now I can use
@google search 林檎
But I can't use
@google 林檎
@google translate 林檎 ja en
can the latter two input and possibly others also add multilingual input?

**Comment by devsnek** [comment]
fixed in 7aa6c907bb2ef3b750b34b77fc33f56db2fcbfa1

**Comment by c933103** [comment]
@google translate 林檎 ja en still is not working

**Comment by devsnek** [comment]
@c933103 not an issue on my part, it is the fault of the translation service i use
